// ============================================================
// @soli92/solids — Themed Icon Sets
// Autogenerated by Soli Designer · do not edit manually
//
// Sets:
//   - FANTASY  : scroll, sword, gem
//   - CYBERPUNK: chip, eye, signal
//   - 90S-PARTY: bolt, diamond, star
// ============================================================

import * as React from "react";
import { SolidsIcon, IconProps } from "./SolidsIcon";

// ─────────────────────────────────────────────────────────────
// FANTASY SET
// Style: rounded strokes, organic shapes, medieval/magic feel
// strokeLinecap="round" strokeLinejoin="round" enforced by SolidsIcon
// ─────────────────────────────────────────────────────────────

/**
 * IconFantasyScroll
 * Rolled parchment scroll with decorative ribbons and central text lines.
 * Organic, soft-cornered geometry. Readable at 20px.
 */
export const IconFantasyScroll = React.forwardRef<SVGSVGElement, IconProps>(
  function IconFantasyScroll(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Outer scroll body */}
        <rect x="4" y="5" width="16" height="14" rx="2" ry="2" />
        {/* Top rolled edge — left curl */}
        <path d="M4 5 C4 3 6 2 7 3 C8 4 7 5 6 5" />
        {/* Top rolled edge — right curl */}
        <path d="M20 5 C20 3 18 2 17 3 C16 4 17 5 18 5" />
        {/* Bottom rolled edge — left curl */}
        <path d="M4 19 C4 21 6 22 7 21 C8 20 7 19 6 19" />
        {/* Bottom rolled edge — right curl */}
        <path d="M20 19 C20 21 18 22 17 21 C16 20 17 19 18 19" />
        {/* Text lines on scroll */}
        <line x1="7" y1="9"  x2="17" y2="9"  />
        <line x1="7" y1="12" x2="17" y2="12" />
        <line x1="7" y1="15" x2="13" y2="15" />
        {/* Small decorative wax-seal dot */}
        <circle cx="15.5" cy="15" r="1" />
      </SolidsIcon>
    );
  }
);

/**
 * IconFantasySword
 * Medieval sword: tapered blade, ornate crossguard, rounded pommel.
 * Diagonal orientation (45°) for iconic readability.
 */
export const IconFantasySword = React.forwardRef<SVGSVGElement, IconProps>(
  function IconFantasySword(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Blade — main diagonal line */}
        <line x1="5" y1="19" x2="17" y2="7" />
        {/* Blade edge taper (second parallel line closing tip) */}
        <path d="M15.5 5.5 L18.5 8.5 L17 7 Z" />
        {/* Tip accent */}
        <path d="M17 7 L19 5" />
        {/* Crossguard — perpendicular bar */}
        <path d="M8 16 C7 14 5 13 4 14 C3 15 4 17 6 16" />
        <path d="M10 14 C11 12 13 11 14 12" />
        <line x1="7" y1="17" x2="13" y2="11" />
        {/* Grip wrapping — small cross-hatches */}
        <line x1="6"  y1="18" x2="7"  y2="17" />
        <line x1="5"  y1="19" x2="6"  y2="18" />
        {/* Pommel — circle at hilt base */}
        <circle cx="4.5" cy="19.5" r="1.5" />
      </SolidsIcon>
    );
  }
);

/**
 * IconFantasyGem
 * Hexagonal magic gem with light-ray burst.
 * Geometric facets + organic ray strokes.
 */
export const IconFantasyGem = React.forwardRef<SVGSVGElement, IconProps>(
  function IconFantasyGem(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Hexagonal gem body */}
        <polygon points="12,3 18,6.5 18,13.5 12,17 6,13.5 6,6.5" />
        {/* Internal facet lines */}
        <line x1="12" y1="3"  x2="12" y2="17" />
        <line x1="6"  y1="6.5"  x2="18" y2="13.5" />
        <line x1="18" y1="6.5"  x2="6"  y2="13.5" />
        {/* Light rays emanating from gem */}
        <line x1="12" y1="1"  x2="12" y2="3"  strokeWidth="1.5" />
        <line x1="19.2" y1="4.5" x2="18" y2="6.5" strokeWidth="1.5" />
        <line x1="21" y1="10" x2="18" y2="10" strokeWidth="1.5" />
        <line x1="19.2" y1="15.5" x2="18" y2="13.5" strokeWidth="1.5" />
        <line x1="12" y1="19" x2="12" y2="17" strokeWidth="1.5" />
        <line x1="4.8" y1="15.5" x2="6" y2="13.5" strokeWidth="1.5" />
        <line x1="3"  y1="10" x2="6"  y2="10" strokeWidth="1.5" />
        <line x1="4.8" y1="4.5" x2="6" y2="6.5" strokeWidth="1.5" />
        {/* Sparkle center dot */}
        <circle cx="12" cy="10" r="1" />
      </SolidsIcon>
    );
  }
);


// ─────────────────────────────────────────────────────────────
// CYBERPUNK SET
// Style: geometric, sharp angles, tech/neon feel
// Uses square corners where possible (overridden via path geometry)
// ─────────────────────────────────────────────────────────────

/**
 * IconCyberpunkChip
 * CPU microchip: square body, evenly spaced pins on all 4 sides,
 * inner circuit cross detail. Pixel-precise geometry.
 */
export const IconCyberpunkChip = React.forwardRef<SVGSVGElement, IconProps>(
  function IconCyberpunkChip(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Chip body */}
        <rect x="6" y="6" width="12" height="12" rx="1" />
        {/* Inner die area */}
        <rect x="9" y="9" width="6" height="6" rx="0" />
        {/* Circuit cross inside die */}
        <line x1="12" y1="9"  x2="12" y2="15" />
        <line x1="9"  y1="12" x2="15" y2="12" />
        {/* Top pins */}
        <line x1="9"  y1="6" x2="9"  y2="3" />
        <line x1="12" y1="6" x2="12" y2="3" />
        <line x1="15" y1="6" x2="15" y2="3" />
        {/* Bottom pins */}
        <line x1="9"  y1="18" x2="9"  y2="21" />
        <line x1="12" y1="18" x2="12" y2="21" />
        <line x1="15" y1="18" x2="15" y2="21" />
        {/* Left pins */}
        <line x1="6" y1="9"  x2="3" y2="9"  />
        <line x1="6" y1="12" x2="3" y2="12" />
        <line x1="6" y1="15" x2="3" y2="15" />
        {/* Right pins */}
        <line x1="18" y1="9"  x2="21" y2="9"  />
        <line x1="18" y1="12" x2="21" y2="12" />
        <line x1="18" y1="15" x2="21" y2="15" />
      </SolidsIcon>
    );
  }
);

/**
 * IconCyberpunkEye
 * Cybernetic eye: sharp almond outline, hex-grid iris,
 * scan-line overlay, mechanical pupil.
 */
export const IconCyberpunkEye = React.forwardRef<SVGSVGElement, IconProps>(
  function IconCyberpunkEye(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Eye outer outline — sharp angular almond */}
        <path d="M2 12 L6 7 L12 5 L18 7 L22 12 L18 17 L12 19 L6 17 Z" />
        {/* Iris circle */}
        <circle cx="12" cy="12" r="4" />
        {/* Scan lines across iris (horizontal) */}
        <line x1="8"  y1="10.5" x2="16" y2="10.5" />
        <line x1="8"  y1="12"   x2="16" y2="12"   />
        <line x1="8"  y1="13.5" x2="16" y2="13.5" />
        {/* Pupil — small rect for mechanical feel */}
        <rect x="10.5" y="10.5" width="3" height="3" rx="0" />
        {/* Corner notch detail — top left */}
        <line x1="6" y1="7"  x2="8"  y2="9"  />
        {/* Corner notch detail — top right */}
        <line x1="18" y1="7"  x2="16" y2="9"  />
        {/* Corner notch detail — bottom left */}
        <line x1="6" y1="17" x2="8"  y2="15" />
        {/* Corner notch detail — bottom right */}
        <line x1="18" y1="17" x2="16" y2="15" />
      </SolidsIcon>
    );
  }
);

/**
 * IconCyberpunkSignal
 * Angular radio signal: 3 concentric chevron-waves (V-shape, not arc),
 * with a square source dot and glitch offset on outermost wave.
 */
export const IconCyberpunkSignal = React.forwardRef<SVGSVGElement, IconProps>(
  function IconCyberpunkSignal(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Source square */}
        <rect x="10" y="10" width="4" height="4" rx="0" />
        {/* Inner angular wave — tight chevron */}
        <path d="M7 8 L5 12 L7 16" />
        <path d="M17 8 L19 12 L17 16" />
        {/* Middle angular wave */}
        <path d="M5 5 L2 12 L5 19" />
        <path d="M19 5 L22 12 L19 19" />
        {/* Outer angular wave — glitch: top segment offset by +1px X */}
        <path d="M3 3 L1 8" />
        {/* glitch break — gap then continue */}
        <path d="M1 14 L3 21" />
        <path d="M21 3 L23 8" />
        <path d="M23 14 L21 21" />
        {/* Glitch horizontal dash to suggest broken signal */}
        <line x1="1"  y1="12" x2="3"  y2="12" />
        <line x1="21" y1="12" x2="23" y2="12" />
      </SolidsIcon>
    );
  }
);


// ─────────────────────────────────────────────────────────────
// 90S-PARTY SET
// Style: bold thick strokes, exaggerated shapes, rave/MTV/Memphis
// Uses strokeWidth="2" on main shapes for extra boldness
// ─────────────────────────────────────────────────────────────

/**
 * IconPartyBolt
 * Thick cartoon lightning bolt, 90s style.
 * Asymmetric, punchy silhouette. Bold stroke.
 */
export const IconPartyBolt = React.forwardRef<SVGSVGElement, IconProps>(
  function IconPartyBolt(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Main bolt shape — closed path for bold fill-ready outline */}
        <polyline
          points="13,2 6,13 11,13 11,22 18,11 13,11"
          strokeWidth="2"
          strokeLinejoin="round"
        />
        {/* Outer shadow/outline offset for double-stroke 90s effect */}
        <polyline
          points="13,2 6,13 11,13 11,22 18,11 13,11"
          strokeWidth="4"
          strokeOpacity="0.18"
          strokeLinejoin="round"
        />
      </SolidsIcon>
    );
  }
);

/**
 * IconPartyDiamond
 * Bold diamond with grunge hip-hop feel.
 * Flat top, wide facets, thick stroke, reflection shard inside.
 */
export const IconPartyDiamond = React.forwardRef<SVGSVGElement, IconProps>(
  function IconPartyDiamond(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Diamond outer body */}
        <polygon
          points="12,2 20,9 12,22 4,9"
          strokeWidth="2"
        />
        {/* Top flat cut — upper facet divider */}
        <line x1="4" y1="9" x2="20" y2="9" strokeWidth="2" />
        {/* Left facet */}
        <line x1="8" y1="9" x2="12" y2="22" />
        {/* Right facet */}
        <line x1="16" y1="9" x2="12" y2="22" />
        {/* Reflection shard — top left highlight */}
        <polyline points="7,9 9,5 12,9" />
        {/* Inner center shine line */}
        <line x1="12" y1="9" x2="12" y2="14" />
      </SolidsIcon>
    );
  }
);

/**
 * IconPartyStar
 * Bold 6-pointed star with double-outline effect.
 * Outer star + inner offset star for retro 90s MTV feel.
 */
export const IconPartyStar = React.forwardRef<SVGSVGElement, IconProps>(
  function IconPartyStar(props, ref) {
    return (
      <SolidsIcon ref={ref} {...props}>
        {/* Outer 6-point star — two overlapping equilateral triangles */}
        {/* Triangle pointing UP */}
        <polygon
          points="12,2 14.8,9.2 22,9.2 16.6,13.8 18.8,21 12,16.4 5.2,21 7.4,13.8 2,9.2 9.2,9.2"
          strokeWidth="2"
        />
        {/* Inner star outline — scaled 65% for double-border effect */}
        <polygon
          points="12,5.8 14,10.8 19.4,10.8 15.2,13.9 16.8,18.8 12,15.7 7.2,18.8 8.8,13.9 4.6,10.8 10,10.8"
          strokeWidth="1"
          strokeOpacity="0.5"
        />
        {/* Center dot accent */}
        <circle cx="12" cy="12" r="1.2" strokeWidth="1.5" />
      </SolidsIcon>
    );
  }
);
